def retrieve(vault: str, key: str) -> str: ...
def squash(vault: str, key: str, depth: int) -> str: ...
def rename(vault: str, old_key: str, new_key: str) -> None: ...
def delete(vault: str, key: str) -> None: ...
def extract(vault: str, key: str, section: str) -> list[str]: ...
def inline(vault: str, key: str, reference: str) -> list[str]: ...
